services:
  - type: web
    name: axtarget-voice
    env: python
    region: frankfurt
    plan: free
    buildCommand: ./build.sh
    startCommand: python app.py
    autoDeploy: true
    envVars:
      PYTHON_VERSION: 3.11.8
